export const userDetails = {
  name: "Nikil.S",
  role: "organizer",
  profile: "profile.png",
  eventsHosted: "3",
  visitors: "1340",
  stalls: "2450",
  nowAttending: "7060",
  liveStall: "1060",
};

export const stallCompletion = {
  completion: [
    { name: "Nikil", status: 20, ocupation: "Jwellery", amount: "Paid" },
    { name: "Nikil", status: 20, ocupation: "Jwellery", amount: "Not Paid" },
    { name: "Nikil", status: 20, ocupation: "Jwellery", amount: "Paid" },
    { name: "Nikil", status: 20, ocupation: "Jwellery", amount: "Not Paid" },
    { name: "Nikil", status: 20, ocupation: "Jwellery", amount: "Paid" },
    { name: "Nikil", status: 20, ocupation: "Jwellery", amount: "Not Paid" },
    { name: "Nikil", status: 20, ocupation: "Jwellery", amount: "Paid" },
    { name: "Nikil", status: 20, ocupation: "Jwellery", amount: "Not Paid" },
    { name: "Nikil", status: 20, ocupation: "Jwellery", amount: "Paid" },
  ],
};
export const exploreEvents = {
  events: [
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "Free Entry",
      banner: "/explore-events/dummy1.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "$5.00 onwards",
      banner: "/explore-events/dummy2.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "$2.99 onwards",
      banner: "/explore-events/dummy3.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "Free Entry",
      banner: "/explore-events/dummy4.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "Free Entry",
      banner: "/explore-events/dummy1.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "$5.00 onwards",
      banner: "/explore-events/dummy2.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "$2.99 onwards",
      banner: "/explore-events/dummy3.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "Free Entry",
      banner: "/explore-events/dummy4.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "Free Entry",
      banner: "/explore-events/dummy1.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "$5.00 onwards",
      banner: "/explore-events/dummy2.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "$2.99 onwards",
      banner: "/explore-events/dummy3.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "Free Entry",
      banner: "/explore-events/dummy4.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "Free Entry",
      banner: "/explore-events/dummy1.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "$5.00 onwards",
      banner: "/explore-events/dummy2.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "$2.99 onwards",
      banner: "/explore-events/dummy3.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "Free Entry",
      banner: "/explore-events/dummy4.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "Free Entry",
      banner: "/explore-events/dummy1.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "$5.00 onwards",
      banner: "/explore-events/dummy2.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "$2.99 onwards",
      banner: "/explore-events/dummy3.svg",
    },
    {
      name: "Lorem Ipsum",
      place: "10Downing St., London",
      price: "Free Entry",
      banner: "/explore-events/dummy4.svg",
    },
  ],
};

export const searchData = [
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Product XYZ",
    categories: ["Electronics Store"],
    subcategories: ["Laptops and Computers"],
    id: "ProductXYZ",
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Widget Alpha",
    categories: ["Bookstore"],
    subcategories: ["Fiction"],
    id: "WidgetAlpha",
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Gadget Z",
    categories: ["Toy Store"],
    subcategories: ["Board Games and Puzzles"],
    id: "GadgetZ",
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Item PQR",
    categories: ["Electronics Store"],
    subcategories: ["Smartphones and Accessories"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 2",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Tool Beta",
    categories: ["Grocery Store"],
    subcategories: ["Fresh Produce"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Device LMN",
    categories: ["Grocery Store"],
    subcategories: ["Dairy and Eggs"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 3",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Accessory Gamma",
    categories: ["Electronics Store"],
    subcategories: ["Laptops and Computers"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Product 12345",
    categories: ["Electronics Store"],
    subcategories: ["Smartphones and Accessories"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Machine Delta",
    categories: ["Bookstore"],
    subcategories: ["Non-Fiction"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 4",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Part KLMNO",
    categories: ["Electronics Store"],
    subcategories: ["Laptops and Computers"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Product XYZ",
    categories: ["Toy Store"],
    subcategories: ["Action Figures"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Widget Alpha",
    categories: ["Bookstore"],
    subcategories: ["Fiction"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Gadget Z",
    categories: ["Toy Store"],
    subcategories: ["Board Games and Puzzles"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Item PQR",
    categories: ["Electronics Store"],
    subcategories: ["Smartphones and Accessories"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 5",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Tool Beta",
    categories: ["Electronics Store"],
    subcategories: ["Laptops and Computers"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Device LMN",
    categories: ["Grocery Store"],
    subcategories: ["Fresh Produce"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 5",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Accessory Gamma",
    categories: ["Toy Store"],
    subcategories: ["Action Figures"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 3",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Product 12345",
    categories: ["Bookstore"],
    subcategories: ["Non-Fiction"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Machine Delta",
    categories: ["Toy Store"],
    subcategories: ["Board Games and Puzzles"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 2",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Part KLMNO",
    categories: ["Fashion Boutique"],
    subcategories: ["Women's Apparel"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Product XYZ",
    categories: ["Electronics Store"],
    subcategories: ["Smartphones and Accessories"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 4",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Widget Alpha",
    categories: ["Grocery Store"],
    subcategories: ["Dairy and Eggs"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Gadget Z",
    categories: ["Toy Store"],
    subcategories: ["Action Figures"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 5",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Item PQR",
    categories: ["Fashion Boutique"],
    subcategories: ["Men's Apparel"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Tool Beta",
    categories: ["Toy Store"],
    subcategories: ["Board Games and Puzzles"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Device LMN",
    categories: ["Fashion Boutique"],
    subcategories: ["Women's Apparel"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 3",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Accessory Gamma",
    categories: ["Grocery Store"],
    subcategories: ["Fresh Produce"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Product 12345",
    categories: ["Bookstore"],
    subcategories: ["Fiction"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 2",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Machine Delta",
    categories: ["Electronics Store"],
    subcategories: ["Smartphones and Accessories"],
  },
  {
    image: "https://picsum.photos/id/237/200/300",
    hall: "hall 1",
    content:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five unchanged.",
    name: "Part KLMNO",
    categories: ["Fashion Boutique"],
    subcategories: ["Men's Apparel"],
  },
];

export const profileModel = {
  datas: [
    {
      stallName: "The Hitchhiker's Guide to the Galaxy",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1979-10-12",
      file: "true",
    },
  ],
};

export const videoModel = {
  datas: [
    {
      stallName: "The Hitchhiker's Guide to the Galaxy",
      stallProduct: "Book",
      video: "Qj0Qx8HpNUo",
      date: "1979-10-12",
      file: "true",
    },
  ],
};

export const breifcaseModel = {
  datas: [
    {
      stallName: "The Hitchhiker's Guide to the Galaxy",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1979-10-12",
      file: "true",
    },
    {
      stallName: "Dune",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1965-06-01",
      file: "false",
    },
    {
      stallName: "Ender's Game",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1985-01-15",
      file: "true",
    },
    {
      stallName: "1984",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1949-06-08",
      file: "true",
    },
    {
      stallName: "Foundation",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1951-05-01",
      file: "false",
    },
    {
      stallName: "Neuromancer",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1984-07-01",
      file: "true",
    },
    {
      stallName: "Brave New World",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1932-01-01",
      file: "true",
    },
    {
      stallName: "Snow Crash",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1992-06-02",
      file: "true",
    },
    {
      stallName: "The Martian",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "2011-09-27",
      file: "true",
    },
    {
      stallName: "I, Robot",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1950-12-02",
      file: "true",
    },
    {
      stallName: "The War of the Worlds",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1898-01-01",
      file: "true",
    },
    {
      stallName: "Fahrenheit 451",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1953-10-19",
      file: "true",
    },
    {
      stallName: "Starship Troopers",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1959-12-01",
      file: "true",
    },
    {
      stallName: "Do Androids Dream of Electric Sheep?",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1968-06-01",
      file: "true",
    },
    {
      stallName: "The Time Machine",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1895-05-07",
      file: "true",
    },
    {
      stallName: "The Handmaid's Tale",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1985-09-01",
      file: "true",
    },
    {
      stallName: "The Hunger Games",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "2008-09-14",
      file: "true",
    },
    {
      stallName: "The Lord of the Rings",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1954-07-29",
      file: "true",
    },
    {
      stallName: "Divergent",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "2011-04-25",
      file: "true",
    },
    {
      stallName: "The Matrix",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1999-03-31",
      file: "true",
    },
    {
      stallName: "The Giver",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1993-04-26",
      file: "true",
    },
    {
      stallName: "The Maze Runner",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "2009-10-06",
      file: "true",
    },
    {
      stallName: "Ready Player One",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "2011-08-16",
      file: "true",
    },
    {
      stallName: "A Wrinkle in Time",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1962-01-01",
      file: "true",
    },
    {
      stallName: "The Warlock of Firetop Mountain",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1982-08-31",
      file: "true",
    },
    {
      stallName: "The Forever War",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1974-06-01",
      file: "true",
    },
    {
      stallName: "The Chronicles of Narnia",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1950-10-16",
      file: "true",
    },
    {
      stallName: "The Expanse",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "2011-06-15",
      file: "true",
    },
    {
      stallName: "The Stand",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1978-09-11",
      file: "true",
    },
    {
      stallName: "The Hitchhiker's Guide to the Galaxy",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1979-10-12",
      file: "true",
    },
    {
      stallName: "Dune",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1965-06-01",
      file: "true",
    },
    {
      stallName: "Ender's Game",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1985-01-15",
      file: "true",
    },
    {
      stallName: "1984",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1949-06-08",
      file: "true",
    },
    {
      stallName: "Foundation",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1951-05-01",
      file: "true",
    },
    {
      stallName: "Neuromancer",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1984-07-01",
      file: "true",
    },
    {
      stallName: "Brave New World",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1932-01-01",
      file: "true",
    },
    {
      stallName: "Snow Crash",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1992-06-02",
      file: "true",
    },
    {
      stallName: "The Martian",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "2011-09-27",
      file: "true",
    },
    {
      stallName: "I, Robot",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1950-12-02",
      file: "true",
    },
    {
      stallName: "The War of the Worlds",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1898-01-01",
      file: "true",
    },
    {
      stallName: "Fahrenheit 451",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1953-10-19",
      file: "true",
    },
    {
      stallName: "Starship Troopers",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1959-12-01",
      file: "true",
    },
    {
      stallName: "Do Androids Dream of Electric Sheep?",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1968-06-01",
      file: "true",
    },
    {
      stallName: "The Time Machine",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1895-05-07",
      file: "true",
    },
    {
      stallName: "The Handmaid's Tale",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1985-09-01",
      file: "true",
    },
    {
      stallName: "The Hunger Games",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "2008-09-14",
      file: "true",
    },
    {
      stallName: "The Lord of the Rings",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1954-07-29",
      file: "true",
    },
    {
      stallName: "Divergent",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "2011-04-25",
      file: "true",
    },
    {
      stallName: "The Matrix",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1999-03-31",
      file: "true",
    },
    {
      stallName: "The Giver",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1993-04-26",
      file: "true",
    },
    {
      stallName: "The Maze Runner",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "2009-10-06",
      file: "true",
    },
    {
      stallName: "Ready Player One",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "2011-08-16",
      file: "true",
    },
    {
      stallName: "A Wrinkle in Time",
      stallProduct: "Book",
      pdfFile:
        "https://nett.umich.edu/sites/default/files/docs/pdf_files_scan_create_reducefilesize.pdf",
      date: "1962-01-01",
      file: "true",
    },
  ],
};

export const eventsAll = {
  events: [
    {
      eventId: "1",
      name: "UK Event",
      color: "#AA2AE8",
      stalls: "456",
      visitors: "2567",
      stallStatus: "90",
      uniqueVisitors: "2156",
      ended: true,
    },
    {
      eventId: "2",
      name: "France Event",
      color: "#006BFF",
      stalls: "726",
      visitors: "1567",
      stallStatus: "50",
      uniqueVisitors: "1106",
      ended: true,
    },
    {
      eventId: "3",
      name: "Germany Event",
      color: "#FE972C",
      stalls: "896",
      visitors: "6567",
      stallStatus: "20",
      uniqueVisitors: "4106",
    },
    {
      eventId: "4",
      name: "Germany Event",
      color: "#FD454A",
      stalls: "696",
      visitors: "4567",
      stallStatus: "75",
      uniqueVisitors: "2006",
      ended: false,
    },
    {
      eventId: "5",
      name: "Ireland Event",
      color: "#F7CC1F",
      stalls: "1096",
      visitors: "8567",
      stallStatus: "60",
      uniqueVisitors: "8106",
      ended: false,
    },
    {
      eventId: "6",
      name: "Malysia Event",
      color: "#13CDF8",
      stalls: "196",
      visitors: "1567",
      stallStatus: "80",
      uniqueVisitors: "906",
      ended: false,
    },
  ],
};

export const visitorsData = [
  {
    name: "Hars Manj",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Rafael Wintheiser Jr.",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Jerome Becker",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "true",
    isApprove: false,
  },
  {
    name: "Milton MacGyver",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: true,
  },
  {
    name: "Sonja Feest",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Holly Altenwerth",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Kimberly Koelpin",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Theresa Miller",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Silvia Zulauf",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Hars Manj",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Rafael Wintheiser Jr.",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Jerome Becker",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "true",
    isApprove: false,
  },
  {
    name: "Milton MacGyver",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: true,
  },
  {
    name: "Sonja Feest",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Holly Altenwerth",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Kimberly Koelpin",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Theresa Miller",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Silvia Zulauf",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Hars Manj",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Rafael Wintheiser Jr.",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Jerome Becker",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "true",
    isApprove: false,
  },
  {
    name: "Milton MacGyver",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: true,
  },
  {
    name: "Sonja Feest",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Holly Altenwerth",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Kimberly Koelpin",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Theresa Miller",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Silvia Zulauf",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Hars Manj",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Rafael Wintheiser Jr.",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Jerome Becker",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "true",
    isApprove: false,
  },
  {
    name: "Milton MacGyver",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: true,
  },
  {
    name: "Sonja Feest",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Holly Altenwerth",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Kimberly Koelpin",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Theresa Miller",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Silvia Zulauf",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Hars Manj",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Rafael Wintheiser Jr.",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Jerome Becker",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "true",
    isApprove: false,
  },
  {
    name: "Milton MacGyver",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: true,
  },
  {
    name: "Sonja Feest",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Holly Altenwerth",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Kimberly Koelpin",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Theresa Miller",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Silvia Zulauf",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Hars Manj",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Rafael Wintheiser Jr.",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Jerome Becker",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "true",
    isApprove: false,
  },
  {
    name: "Milton MacGyver",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: true,
  },
  {
    name: "Sonja Feest",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Holly Altenwerth",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Kimberly Koelpin",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Theresa Miller",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Silvia Zulauf",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Hars Manj",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Rafael Wintheiser Jr.",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Jerome Becker",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "true",
    isApprove: false,
  },
  {
    name: "Milton MacGyver",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: true,
  },
  {
    name: "Sonja Feest",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Holly Altenwerth",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Kimberly Koelpin",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Theresa Miller",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Silvia Zulauf",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Hars Manj",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Rafael Wintheiser Jr.",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Jerome Becker",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "true",
    isApprove: false,
  },
  {
    name: "Milton MacGyver",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: true,
  },
  {
    name: "Sonja Feest",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Holly Altenwerth",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Kimberly Koelpin",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Theresa Miller",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Silvia Zulauf",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Hars Manj",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Rafael Wintheiser Jr.",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Jerome Becker",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "true",
    isApprove: false,
  },
  {
    name: "Milton MacGyver",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: true,
  },
  {
    name: "Sonja Feest",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Holly Altenwerth",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Kimberly Koelpin",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Theresa Miller",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Silvia Zulauf",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Hars Manj",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Rafael Wintheiser Jr.",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Jerome Becker",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "true",
    isApprove: false,
  },
  {
    name: "Milton MacGyver",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: true,
  },
  {
    name: "Sonja Feest",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Holly Altenwerth",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Kimberly Koelpin",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Theresa Miller",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Silvia Zulauf",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Hars Manj",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Rafael Wintheiser Jr.",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Jerome Becker",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: "true",
    isApprove: false,
  },
  {
    name: "Milton MacGyver",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "Mr.Jack",
    breifcase: "",
    isView: false,
    isApprove: true,
  },
  {
    name: "Sonja Feest",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Holly Altenwerth",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
  {
    name: "Kimberly Koelpin",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "false",
    isApprove: true,
  },
  {
    name: "Theresa Miller",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: false,
    isApprove: false,
  },
  {
    name: "Silvia Zulauf",
    company: "Juniper",
    mail: "manju@gmail.com",
    phone: "+9195874555",
    vip: "",
    breifcase: "",
    isView: "true",
    isApprove: true,
  },
];

export const eventsData = [
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },

  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },

  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
  {
    title: "Uk Fair",
    startDate: "7-11-2023",
    endDate: "10-11-2023",
    fairTime: "9:00 AM",
    status: "on-live",
    action: "Click Here",
  },
];

export const faqData = [
  {
    title: "What are your other upcoming events?",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "What is IIHS?",
    description: `HHS fair mainly connects buyers and sellers in bed linen, table linen, toilet and
        kitchen linen, towels, curtains, cushions and pads, tapestries and upholstery, carpets
        and floor coverings, clothing accessories, fabrics etc.`,
  },
  {
    title: "What can participate?",
    description: `HHS fair mainly connects buyers and sellers in bed linen, table linen, toilet and
        kitchen linen, towels, curtains, cushions.`,
  },
];

export const exhibitorLoginData = [
  {
    name: "Texas international",
    email: "m1@texas.com",
    password: "hi@123",
  },
  {
    name: "Texas international",
    email: "m1@texas.com",
    password: "hi@123",
  },
  {
    name: "Texas international",
    email: "m1@texas.com",
    password: "hi@123",
  },
  {
    name: "Texas international",
    email: "m1@texas.com",
    password: "hi@123",
  },
  {
    name: "Texas international",
    email: "m1@texas.com",
    password: "hi@123",
  },
  {
    name: "Texas international",
    email: "m1@texas.com",
    password: "hi@123",
  },
  {
    name: "Texas international",
    email: "m1@texas.com",
    password: "hi@123",
  },
  {
    name: "Texas international",
    email: "m1@texas.com",
    password: "hi@123",
  },
];

export const reportsData = [
  {
    column1: "Lorem",
    column2: "Ipsum",
    column3: "Dolor",
    column4: "Init",
    column5: "Lorem",
    column6: "Ipsum",
    column7: "Dolor",
    column8: "Init",
    column9: "Lorem",
    column10: "Ipsum",
  },
  {
    column1: "Lorem",
    column2: "Ipsum",
    column3: "Dolor",
    column4: "Init",
    column5: "Lorem",
    column6: "Ipsum",
    column7: "Dolor",
    column8: "Init",
    column9: "Lorem",
    column10: "Ipsum",
  },
  {
    column1: "Lorem",
    column2: "Ipsum",
    column3: "Dolor",
    column4: "Init",
    column5: "Lorem",
    column6: "Ipsum",
    column7: "Dolor",
    column8: "Init",
    column9: "Lorem",
    column10: "Ipsum",
  },
  {
    column1: "Lorem",
    column2: "Ipsum",
    column3: "Dolor",
    column4: "Init",
    column5: "Lorem",
    column6: "Ipsum",
    column7: "Dolor",
    column8: "Init",
    column9: "Lorem",
    column10: "Ipsum",
  },
  {
    column1: "Lorem",
    column2: "Ipsum",
    column3: "Dolor",
    column4: "Init",
    column5: "Lorem",
    column6: "Ipsum",
    column7: "Dolor",
    column8: "Init",
    column9: "Lorem",
    column10: "Ipsum",
  },
  {
    column1: "Lorem",
    column2: "Ipsum",
    column3: "Dolor",
    column4: "Init",
    column5: "Lorem",
    column6: "Ipsum",
    column7: "Dolor",
    column8: "Init",
    column9: "Lorem",
    column10: "Ipsum",
  },
];

export const activityData = [
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
  {
    title: "Inaugral Address",
    time: "09:30 - 10:30",
    description:
      "Check https://www.googl.com for other official updates regarding our future events.",
  },
];
